version: '3'
services:
  web:
    image: nginx:stable-alpine3.17
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./web:/var/www/html
    ports:
      - 8080:80
    command: "nginx -g 'daemon off;'"
    depends_on:
      - fpm
      - db
  fpm:
    build: ./docker/fpm/
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ./web:/var/www/html
  db:
    image: mariadb:11.1.2
    volumes:
      - ./config/structure.sql:/docker-entrypoint-initdb.d/structure.sql
      - ./data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
  cron:
    build: ./docker/cron/
    volumes:
      - ./config/cron.txt:/crontab